spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.176.44:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  data:
    redis:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true

  cache:
    type: redis
    redis:
      time-to-live: 600000  #缓存有效时长ms
      cache-null-values: false #是否允许空值

  redis:
    host: 101.42.176.44
    port: 6379
    password:
    timeout: 5000
    database: 0
    jedis:
      pool:  #连接池配置
        max-active: 100 #最大连接数
        max-wait: 100ms #最大等待连接超时时间
        max-idle: 100 #最大维持连接数
        min-idle: 10  #最小维持连接数





logging:
  level:
    root: info
    com.lrm: debug
  file:
    path: log/blog-dev.log



