server:
  port: 81
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 169167866Spl.
  data:
    redis:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  cache:
    type: redis
    redis:
      time-to-live: 600000  #缓存有效时长ms
      cache-null-values: false #是否允许空值
    cache-names: blog,tag,tag-name,type,type-name,user   #通过默认的RedisCacheManager在启动时创建其缓存空间

  redis:
    host: localhost
    port: 6379
    timeout: 5000
    database: 0

logging:
  level:
    root: info
    com.lrm: debug
  file:
    path: log/blog-dev.log



