spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.176.44:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
#  cache:
#    type: redis
#  redis:
#    host: 101.42.176.44
#    port: 6379
#    client-type: lettuce

logging:
  level:
    root: info
    com.lrm: debug
  file:
    path: log/blog-dev.log



