spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.176.44:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  data:
    redis:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  cache:
    type: redis
    redis:
      time-to-live: 600000  #缓存有效时长ms
      cache-null-values: false #是否允许空值
    cache-names: blog,comment,tag,tag-name,type,type-name,user   #通过默认的RedisCacheManager在启动时创建其缓存空间


  redis:
    host: 101.42.176.44
    port: 6379
    password:
    timeout: 5000
    database: 0

logging:
  level:
    root: warn
    com.lrm: info
  file:
    path: log/blog-pro.log
server:
  port: 8081






